import Head from "next/head"
import Image from "next/image"
import { useRouter } from "next/router"
import { useEffect, useState, useCallback } from "react"
import { Images } from "../../utils/images"
import { Text } from "../../components/text"
import { Navbar } from "../../components/navabr"
import { Footer } from "../../components/footer"
import { WorkCard } from "../../components/card/work"
import { EducationCard } from "../../components/card/education"
import { BookOpen, Flag, MapPin, User } from "react-feather"
import { DataTable } from "../../components/table"
import { NoContent } from "../../components/no-content"
import { NetworkError } from "../../components/network-error"
import { ResearcherShowPreloader } from "../../components/preloader"
import { ResearcherPublicProfile, ResearcherPublications } from "../../pages/api"

const index = () => {
    const router = useRouter()
    const { username } = router.query
    const [data, setData] = useState()
    const [isLoading, setLoading] = useState(true)
    const [serverError, setServerError] = useState(false)

    const [perPage, setPerPage] = useState(20)
    const [totalRows, setTotalRows] = useState(0)
    const [publication, setPublication] = useState({ isLoading: true, data: [] })

    /* fetch data */
    const fetchData = useCallback(async () => {
        try {
            const response = await ResearcherPublicProfile(username)
            if (response && response.status === 200) {
                setData(response.data.data)
                setLoading(false)
            } else {
                setLoading(false)
                setServerError(true)
            }
        } catch (error) {
            if (error) {
                setLoading(false)
                setServerError(true)
                console.log(error.response)
            }
        }
    }, [username])

    /* fetch publication */
    const fetchPublications = useCallback(async (username, page) => {
        try {
            setPublication({ ...publication, isLoading: true })
            const response = await ResearcherPublications(username, page, perPage)
            if (response.status === 200 && response.data.data.length > 0) {
                console.log(response.data.data);
                setPublication({ isLoading: false, data: response.data.data })
                setTotalRows(response.data.pagination?.response.data.pagination.total_items)
            }
            // setPublication({ ...publication, isLoading: false })
            // setPublication(exPublication => ({ ...exPublication, isLoading: false }))
        } catch (error) {
            if (error) {
                setPublication({ ...publication, isLoading: false })
                console.log(error.response)
            }
        }
    }, [username, perPage])

    useEffect(() => {
        fetchData()
    }, [username, fetchData])

    useEffect(() => {
        if (username) fetchPublications(username, 1)
    }, [username, fetchPublications])

    // handle paginate page change
    const handlePageChange = page => fetchPublications(username, page)

    // handle paginate row change
    const handlePerRowsChange = async (newPerPage, page) => {
        setPublication({ ...publication, isLoading: true })
        const response = await ResearcherPublications(username, page, newPerPage)
        setPublication({ isLoading: false, data: response.data.data })
        setPerPage(newPerPage)
    }

    // data columns
    const columns = [
        {
            name: "Date",
            sortable: true,
            selector: row => row.publicationDate || "N/A"
        },
        {
            name: "Title",
            sortable: true,
            selector: row => row.title
        }
    ]

    return (
        <div>
            <Head>
                <title>ResearchTop || researcher profiles</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar user={""} />

            <div className="container mx-auto mt-[74px] py-[30px]">

                {isLoading && !serverError && !data ? <ResearcherShowPreloader /> : null}
                {!isLoading && !serverError && !data ? <NoContent message="No content available." /> : null}
                {!isLoading && serverError && !data ? <NetworkError /> : null}

                {!isLoading && !serverError && data ?
                    <div className="grid grid-cols-1">
                        <div className="lg:flex">

                            {/* Profile information */}
                            <div className="w-full lg:w-[350px] mb-10 lg:mb-0 lg:pr-5">
                                <div className="text-center lg:text-left mb-4">
                                    <Image
                                        src={Images.Avatar}
                                        alt="avatar"
                                        width={150}
                                        height={150}
                                    />

                                    <Text className="text-md font-medium capitalize">{data?.name}</Text>
                                </div>

                                <div>

                                    {/* About */}
                                    <Text className="text-sm font-normal text-gray-500 mb-3">{data?.about}</Text>

                                    {/* Address */}
                                    <table className="table-auto mb-4">
                                        <tbody>
                                            <tr>
                                                <td className="w-[25px]">
                                                    <MapPin size={16} />
                                                </td>
                                                <td>
                                                    <Text className="text-sm font-normal text-gray-500">{data?.address}</Text>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td className="w-[25px]">
                                                    <Flag size={16} />
                                                </td>
                                                <td>
                                                    <Text className="text-sm font-normal text-gray-500">{data?.country}</Text>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td className="w-[25px]">
                                                    <BookOpen size={16} />
                                                </td>
                                                <td>
                                                    <Text className="text-sm font-normal text-gray-500">{data?.publications} publications</Text>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td className="w-[25px]">
                                                    <User size={16} />
                                                </td>
                                                <td>
                                                    <Text className="text-sm font-normal text-gray-500">
                                                        www.researchtop/researcher/{data?.username}
                                                    </Text>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>

                                    {/* Work experience */}
                                    {data && data.work && data.work.length > 0 ?
                                        <div className="mb-4">
                                            <Text className="text-sm font-medium mb-3">Work experience</Text>

                                            {data.work.map((item, i) =>
                                                <WorkCard
                                                    key={i}
                                                    data={item}
                                                />
                                            )}
                                        </div>
                                        : null
                                    }

                                    {/* Education */}
                                    {data && data.education && data.education.length > 0 ?
                                        <div>
                                            <Text className="text-sm font-medium mb-3">Education</Text>

                                            {data.education.map((item, i) =>
                                                <EducationCard
                                                    key={i}
                                                    data={item}
                                                />
                                            )}
                                        </div>
                                        : null
                                    }

                                    {/* Other profiles */}
                                    <div>
                                        <Text className="text-sm font-medium mb-3">Other profiles</Text>
                                    </div>
                                </div>
                            </div>

                            {/* Publications list */}
                            <div className="grow p-5">
                                <DataTable
                                    data={publication.data}
                                    columns={columns}
                                    loading={publication.isLoading}
                                    totalRows={totalRows}
                                    handlePerRowsChange={handlePerRowsChange}
                                    handlePageChange={handlePageChange}
                                    noDataMessage="Publications not available."
                                />
                            </div>
                        </div>
                    </div>
                    : null
                }

            </div>


            <Footer />
        </div>
    );
};

export default index;