import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import { useEffect, useState } from "react"
import { Images } from "../../utils/images"
import { Text } from "../../components/text"
import { Navbar } from "../../components/navabr"
import { Footer } from "../../components/footer"
import { PrimaryButton } from "../../components/button"
import { ResearcherPreloader } from "../../components/preloader"

const index = () => {
    const [isLoading, setLoading] = useState(true)
    const [data, setData] = useState([])

    useEffect(() => {
        setTimeout(() => {
            setData([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
            setLoading(false)
        }, 3000)
    }, [])

    return (
        <div>
            <Head>
                <title>ResearchTop || researcher profiles</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar user={""} />

            <div className="container mx-auto mt-[74px]">
                <div className="grid grid-cols-1 text-center py-8">
                    <Text className="text-xl font-regular text-gray-600">Browse researcher</Text>
                </div>
            </div>

            {isLoading && !data.length ? <ResearcherPreloader length={12} /> : null}

            {!isLoading && data.length > 0 ?
                <div className="container mx-auto mb-14">
                    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5 text-center gap-8">

                        {data && data.map((item, i) =>
                            <Link href={`/researcher/${item}`} key={i}>
                                <a>
                                    <div className="w-[250px] sm:w-full mx-auto p-8 border rounded-2xl hover:border-white hover:shadow-xl transition-all cursor-pointer">
                                        <Image
                                            src={Images.Avatar}
                                            alt="User avatar"
                                            width={100}
                                            height={100}
                                        />

                                        <Text className="text-md font-normal mt-2">abcd xyz</Text>
                                    </div>
                                </a>
                            </Link>
                        )}

                    </div>
                </div>
                : null
            }

            {!isLoading && data.length > 0 ?
                <div className="container mx-auto">
                    <div className="grid grid-cols-1 text-center pb-12">
                        <div>
                            <PrimaryButton>Show more</PrimaryButton>
                        </div>
                    </div>
                </div>
                : null
            }

            <Footer />
        </div>
    );
};

export default index;