import Head from "next/head"
import { Navbar } from "../components/navabr"
import { Footer } from "../components/footer"

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar user={""} />

      <div className="bg-indigo-400 h-[500px]"></div>

      <Footer />
    </div>
  )
}
