import Head from "next/head"
import { useState } from "react"
import { Navbar } from "../components/navabr"
import { Drawer } from "../components/drawer"

export default function Home() {
  const [show, setShow] = useState(false)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar
        user={""}
        handleDrawer={() => setShow(!show)}
      />

      <Drawer
        show={show}
        hidden={"lg"}
        onClick={() => setShow(!show)}
      />

    </div>
  )
}
